blueprint:
    name: Philips Hue Tap Dial Brightness Control
    description: Uses Zigbee2MQTT connected Tap Dial to control light brightness
    domain: automation
    author: Ronaldo Pace
    input:
        # The philips hue tap dial device connected to the Zigbee2MQTT
        mqtt_topic:
            name: MQTT Topic
            description: The MQTT topic for the Philips Hue Tap Dial.<br><br>
                This is composed by combining:<br>
                - the MQTT base name (defaults to 'zigbee2mqtt')<br>
                - the slash '/' symbol <br>
                - the name of the device <br><br>
                The value can be found on Zigbee2MQTT page for the device under 'MQTT' section.<br>
                Example 'zigbee2mqtt/Living Room Lights'
        # The light entity to control
        target_light:
            name: Light Entity
            description: The light to control the brightness
            selector:
                entity:
                    domain: light
                    multiple: false
        target_transition:
            name: Light Transition
            description: Adding a very small transition (probably between 0.2 and 0.5) might give a smoother feeling to the light changes
            default: 0
            selector:
                number:
                    step: any
                    unit_of_measurement: seconds
                    mode: box
                    min: 0
                    max: 3

# triggers everytime a new message arrives at the mqtt
triggers:
    -   trigger: mqtt
        topic: !input mqtt_topic

conditions:

    # only process the proper mqtt payloads
    -   condition: template
        value_template: >-
            {{ trigger.payload_json.action == 'brightness_step_up' or
            trigger.payload_json.action == 'brightness_step_down' }}

actions:

    # computes the brightness change proportional to the tap dial step
    -   variables:
            step: "{{ trigger.payload_json.action_step_size / 4.23 }}"
            action: "{{ trigger.payload_json.action }}"

    -   choose:
            -   alias: Brightness Up
                conditions:
                    -   condition: template
                        value_template: "{{ action == 'brightness_step_up' }}"
                sequence:
                    -   action: light.turn_on
                        data:
                            brightness_step_pct: "{{ step }}"
                            transition: !input target_transition
                        target:
                            entity_id: !input target_light

            -   alias: Brightness Down
                conditions:
                    -   condition: template
                        value_template: "{{ action == 'brightness_step_down' }}"
                sequence:
                    -   action: light.turn_on
                        data:
                            brightness_step_pct: "{{ step * -1 }}"
                            transition: !input target_transition
                        target:
                            entity_id: !input target_light
mode: queued
max: 20
